### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by GinNide** [uxiaohan/hansUrl#1]
您的项目已被我修改为自己的页面 如果您觉得不合适我将删掉此网站

**Comment by uxiaohan** [comment]
好的没问题。
&nbsp;

- 是小韩啊


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gin_Nide"<notifications@github.com&gt;; 
发送时间: 2020年5月27日(星期三) 下午5:31
收件人: "uxiaohan/hansUrl"<hansUrl@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [uxiaohan/hansUrl] 你好 (#1)





 
您的项目已被我修改为自己的页面 如果您觉得不合适我将删掉此网站

**Comment by uxiaohan** [comment]
> 您的项目已被我修改为自己的页面如果您觉得不合适我将删掉此网站

好的，没问题。

**Comment by GinNide** [comment]
非常感谢
